config/routes.rb
Rails.application.routes.draw do

  #生成したコントローラーがどこに存在するかを記述, 不要なルーティングを削除
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  root to: 'public/homes#top'
  get "public/about" => 'public/homes#about'

  #管理者側
  namespace :admin do
    #会員情報
    resources :users
    #投稿
    resources :posts do
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
      end
    end
    
    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end

  #会員側
  namespace :public do
    #トップ
    root to: 'homes#top'
    #ログインユーザー情報
    resources :users , only: [:show, :edit, :update]
    get "users/:id/show_withdraw" => 'users#show_withdraw'
    patch "users/:id/show_withdraw" => 'users#withdraw'
    #投稿
    resources :posts do
      #いいね機能
      resource :favorites, only: [:create, :destroy]
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
       resources :event_notices, only: [:new, :create]
       get "event_notices" => "event_notices#sent"
      end
    end

    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @range = params[:range]#検索範囲
    @word = params[:word]#検索ワード
    @search = params[:search]#検索メソッド
    @posts = Post.all

    if @range == 'User'
      @users = User.search_for(@search, @word)
    elsif @range == 'Post'
      @posts = Post.search_for(@search, @word)
    elsif @range == 'Tag'
      @posts = Tag.search_posts_for(@search, @word)
    end
  end
end

app/views/admin/searches/_tag_form.html.erb
  <div class="search_form">
    <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :word, placeholder: "search" %>
      <%= f.hidden_field :range, :value => "Tag" %>
      <%= f.hidden_field :search, :value => "partial_match" %>
      <%= f.submit 'タグ検索', class: "btn btn-primary" %>
    <% end %>
  </div>

app/views/admin/searches/_text_form.html.erb
<div class="search_form">
  <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, placeholder: "目的・観光地など" %>
    <%= f.select :range, options_for_select([["投稿検索", 'Post'], ["ユーザー検索", 'User']]) %>
    <%= f.select :search, options_for_select([["部分一致","partial_match"], ["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"]]) %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/searches/search.html.erb
<h2>検索結果 "<%= @word %>"</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, admin_user_path(user)  %></td>
        </tr>
      <% end %>
    </tbody>
  <!--検索対象モデルがPostの時-->
  <% elsif @range == 'Post' || @range == 'Tag' %>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, admin_post_path(post) %></td>
          <td>
            <% post.tags.each do |tag| %>
              <li style="list-style: none;"><%= link_to tag.name, admin_search_path(word: tag.name, range:"Tag", search: "perfect_match") %></li>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>