config/routes.rb
Rails.application.routes.draw do

  #生成したコントローラーがどこに存在するかを記述, 不要なルーティングを削除
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  root to: 'public/homes#top'
  get "public/about" => 'public/homes#about'

  #管理者側
  namespace :admin do
    #会員情報
    resources :users
    #投稿
    resources :posts do
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
      end
    end
    
    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end

  #会員側
  namespace :public do
    #トップ
    root to: 'homes#top'
    #ログインユーザー情報
    resources :users , only: [:show, :edit, :update]
    get "users/:id/show_withdraw" => 'users#show_withdraw'
    patch "users/:id/show_withdraw" => 'users#withdraw'
    #投稿
    resources :posts do
      #いいね機能
      resource :favorites, only: [:create, :destroy]
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
       resources :event_notices, only: [:new, :create]
       get "event_notices" => "event_notices#sent"
      end
    end

    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  #アソシエーション
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :group_users, through: :groups, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy

  #一枚の画像添付
  has_one_attached :post_image

  #バリデーション
  validates :title, length: { maximum: 20 }, presence: true
  validates :body, presence: true
  validates :date, presence: true

  #投稿画像添付
  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      post_image.variant(resize_to_limit: [width, height]).processed
  end

  #ユーザーが投稿作成者かの確認
  def is_owned_by?(user)
    self.user == user
  end

  #いいねがされているかの確認
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #タグの保存
  def save_tags(savepost_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

     # 新しいタグを保存
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << post_tag
    end
  end

  # 検索方法分岐
  def self.search_for(search, word)
    if search == "perfect_match" #完全一致
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"#前方一致
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"#後方一致
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"#部分一致
      @post = Post.where("title LIKE?","%#{word}%"). or where("date LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.page(params[:page])
    @tag_list = Tag.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @groups = Group.where(post_id: @post.id)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post), notice: "投稿を更新しました"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  # 投稿データのストロングパラメータ
  private

  def post_params
    params.require(:post).permit(:title, :body, :post_image)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<div class = container>
  <div class = row>
    <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>投稿編集</h1>
        <% if @post.errors.any? %>
          <%= @post.errors.count %>errors prohibited this obj from being saved: 
          <ul>
          <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>             
        <%= form_with model: @post,url: admin_post_path do |f| %>
          <div class="form-group">
            <label for="post_title">タイトル</label>
            <%= f.text_field :title, autofocus: true, placeholder: @post.title, class: "form-control post_title" %>
          </div>
          <div class = "form-group">
            <label for="post_opinion">詳細</label>
            <%= f.text_area :body, autofocus: true, class: "form-control post_body" %>
          </div>
          <div class = "form-group">
            <%= f.submit "更新する", class: "btn btn-success"  %>
          </div>
          <%= link_to "戻る", admin_post_path(@post) %>
          <%= "|" %>
          <%= link_to "投稿一覧へ", admin_posts_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/index.html.erb
<!--投稿一覧-->
<div class="continer">
  <h4 class = "text-center m-3">投稿一覧</h4>
  <div class="card-list-container  py-5">
    <% @posts.each do |post| %>
      <div class="card w-60 mx-auto mt-4 shadow-lg">
        <div class="card-body">
          <div class="row">
            <div class="col-3 text-center">
              <p><%= link_to image_tag(post.user.get_profile_image(50,50), class: "rounded-circle"), admin_user_path(post.user) %></p>
              <span class = "d-flex flex-nowrap justify-content-center"><i class="fas fa-user"></i><%= post.user.name %></span>
            </div>
            <div class="col-9">
              <p class="card-title">タイトル</p>
              <p class="card-text"><%= link_to post.title, admin_post_path(post) %></p>
              <p class="card-title">詳細</p>
              <p class="card-text"><%= safe_join(post.body.split("\n"),tag(:br)) %></p>
              <% post.tags.each do |tag| %>
                <i class="fas fa-tag"></i><%= link_to tag.name, public_search_path(word: tag.name, range:"Tag", search: "perfect_match") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class = "text-center m-3"><%= paginate @posts %></div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<% if flash[:notice] %>
 <div class="alert alert-success" role="alert">
 <p class="notice text-center" style="color:green;"><%= flash[:notice] %></p>
 </div>
<% end %>

<div class = "container text-center">
  <div class = "m-5">
    <%= image_tag @post.get_post_image(200,200) %>
    <p>タイトル：<%= @post.title %></p>
    <p>予定日：<%= @post.date.strftime('%Y/%m/%d') %></p>
    <%= safe_join(@post.body.split("\n"),tag(:br)) %></p>
    <p><%= link_to image_tag(@post.user.get_profile_image(100,100)), admin_user_path(@post.user) %></p>
    <p>ユーザーネーム：<%= @post.user.name %></p>
    <p class="comments_count">コメント数: <%= @post.post_comments.count %></p>
    <p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>
  </div>

  <h3 class = "m-3">グループ</h3>
  <table class = "table table-hover">
    <thead>
     <tr>
        <th>グループ画像</th>
        <th>グループ名</th>
        <th>紹介文</th>
        <th>人数</th>
     </tr>
    </thead>
    <body>
     <% @groups.each do |group| %>
       <tr>
         <td><%= image_tag group.get_group_image(50,50) %></td>
         <td><%= link_to group.name, admin_post_group_path(@post, group) %></td>
         <td><%= group.introduction %></td>
         <td><%= group.users.count %></td>
         <div class = "m-3">
           <td><%= link_to "グループ編集", edit_admin_post_group_path(@post, group), class: "btn btn-sm btn-success edit_group" %></td>
         </div>
       </tr>
     <% end %>
    </body>
  </table>
  <!--コメント一覧-->
  <div class="comments_index">
    <%= render 'admin/post_comments/index', post: @post, post_comment: @post_comment %>
  </div>
  <%= link_to "投稿削除", admin_post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger mb-3 destroy_post "  %>
  <%= link_to "投稿編集", edit_admin_post_path(@post), class: "btn btn-sm btn-success edit_post mb-3 ml-3" %>
</div>