config/routes.rb
Rails.application.routes.draw do

  #生成したコントローラーがどこに存在するかを記述, 不要なルーティングを削除
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  root to: 'public/homes#top'
  get "public/about" => 'public/homes#about'

  #管理者側
  namespace :admin do
    #会員情報
    resources :users
    #投稿
    resources :posts do
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
      end
    end
    
    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end

  #会員側
  namespace :public do
    #トップ
    root to: 'homes#top'
    #ログインユーザー情報
    resources :users , only: [:show, :edit, :update]
    get "users/:id/show_withdraw" => 'users#show_withdraw'
    patch "users/:id/show_withdraw" => 'users#withdraw'
    #投稿
    resources :posts do
      #いいね機能
      resource :favorites, only: [:create, :destroy]
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
       resources :event_notices, only: [:new, :create]
       get "event_notices" => "event_notices#sent"
      end
    end

    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  #アソシエーション
  belongs_to :user
  belongs_to :post
  
  #バリデーション
  validates :comment, presence: true
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to request.referer
  end
  
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<table>
  <tbody>
    <% post.post_comments.each do |post_comment| %>
    <tr>
      <td>
        <%= link_to admin_user_path(post_comment.user) do %>
          <%= image_tag post_comment.user.get_profile_image(100,100) %><br>
          <%= post_comment.user.name %>
        <% end %>
      </td>
      <td><%= post_comment.comment %></td>
      <td>
        <% if admin_signed_in? %>
          <%= link_to "コメント削除", admin_post_post_comment_path(post, post_comment), method: :delete, remote: true, class: "btn btn-danger btn-sm pull-right ml-3" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>