config/routes.rb
Rails.application.routes.draw do

  #生成したコントローラーがどこに存在するかを記述, 不要なルーティングを削除
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  devise_for :user, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲスト側
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  root to: 'public/homes#top'
  get "public/about" => 'public/homes#about'

  #管理者側
  namespace :admin do
    #会員情報
    resources :users
    #投稿
    resources :posts do
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
      end
    end
    
    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end

  #会員側
  namespace :public do
    #トップ
    root to: 'homes#top'
    #ログインユーザー情報
    resources :users , only: [:show, :edit, :update]
    get "users/:id/show_withdraw" => 'users#show_withdraw'
    patch "users/:id/show_withdraw" => 'users#withdraw'
    #投稿
    resources :posts do
      #いいね機能
      resource :favorites, only: [:create, :destroy]
      #コメント機能
      resources :post_comments, only: [:create, :destroy]
      #グループ機能
      resources :groups do
        resource :group_users, only: [:create, :destroy]
        delete "all_destroy" => 'groups#all_destroy'
       resources :event_notices, only: [:new, :create]
       get "event_notices" => "event_notices#sent"
      end
    end

    #検索
    get "search" => 'searches#search'
    get "search_tag"=>"posts#search_tag"
  end










  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!--ヘッダー-->
  <body class="d-flex flex-column vh-100">
   <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand" href="/"><%= image_tag('logo.png') %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <!--管理者（admin）-->
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_users_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_posts_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
            <!--検索フォーム-->
            <%= render "admin/searches/text_form" %>
          <!--会員ユーザー-->
          <% elsif user_signed_in? %>
            <li class="nav-item">
              <%= link_to public_posts_path, class: 'nav-link text-dark' do %>
              <i class="far fa-flag"></i> 投稿一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_user_path(current_user), class: 'nav-link text-dark' do %>
              <i class="fas fa-user"></i> マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
            <!--検索ボタン-->
            <%= render "public/searches/button" %>
          <!--ゲスト、非会員-->
          <% else %>
            <li class="nav-item">
              <%= link_to  public_about_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-link"></i> サイトについて
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  new_user_session_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
            </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
    </header>
    <main>
      <%= yield %>
      <span id="back">
        <a href="#">
          <%= image_tag asset_path('arrow.png'), class: "arrow" %>
        </a>
      </span>
    </main>
    <!--フッター-->
    <footer class="bg-dark text-white pt-5 pb-4">
          <div class="container">
            <div class="row no-gutters">
              <div class="col-md-4">
                <p></p>
              </div>
              <div class="col-md-8">
                <h6 class="text-white mt-2 mb-3">Link</h6>
                <ul class="p-0 list-unstyled">
                  <li>
                    <a href="" title="About" class="text-white-50">会社概要</a>
                  </li>
                  <li>
                    <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
    </footer>
  </body>
</html>